modLoader="javafml"
loaderVersion="[${loader_version},)"
license="All rights reserved"
issueTrackerURL="https://github.com/MeinKraft/Crimson-Junk-Bags/issues" #optional

[[mods]]
modId="crimsonjunkbags"
version="${version}"
displayName="Crimson Junk Bags"
displayURL="https://www.curseforge.com/minecraft/mc-mods/crimson-junk-bags-loot"
updateJSONURL = "https://github.com/MeinKraft/Crimson-Junk-Bags/raw/NBT/update.json"
authors="§4Crimson_Fluff"
logoFile="logo.png" #optional
credits="\n§bTechnovision§r for his awesome modding YouTube series\n§bTurtyWurty§r for his awesome modding YouTube series" #optional
description=''' A basic Loot Bag style mod for 1.16.4+ '''

[[dependencies.crimsonjunkbags]]
    modId="minecraft"
    mandatory=true
    versionRange="[${mc_version}]"
  side="BOTH"
[[dependencies.crimsonjunkbags]]
    modId="forge"
    mandatory=true
    versionRange="[${forge_version},)"
    side="BOTH"
